### ISSUE TITLE
Live lights crash

### ISSUE THREAD

**Issue by getinmybelly1** [pnwparksfan/rph-live-lights#10]
On a clean latest GTA version I installed the most up to date LSPDFR+RagePluginHook files.
I loaded into the game and manually loaded livelights. When pressing "-" to open the UI menu, the plugin crashe
[RagePluginHook.log](https://github.com/pnwparksfan/rph-live-lights/files/7775269/RagePluginHook.log)

**Comment by pnwparksfan** [comment]
[Update RageNativeUI](https://github.com/alexguirre/RAGENativeUI/releases)
