### ISSUE TITLE
Plugin Crashing When Pressing Keybind To Open Menu (.dll)

### ISSUE THREAD

**Issue by TylerLuck** [pnwparksfan/rph-live-lights#13]
When loading into the game with the plugin activated, spawning a car, getting into it, then pressing the key bind to open the menu, a .dll error occurs.

Grand Theft Auto V v1.0.2545.0 Steam
RAGE Plugin Hook v1.90.1298.16281 PUBLIC

![CRASH](https://user-images.githubusercontent.com/101968162/159154161-188a3f51-7634-49ff-8abf-2b2b0705155c.PNG)

**Comment by NOMAD6-1** [comment]
I am having the same problem
