### ISSUE TITLE
Plugin crashes on the latest version of RAGENativeUI

### ISSUE THREAD

**Issue by KIKI66666yt** [pnwparksfan/rph-live-lights#14]
I saw in previous crash reports that the plugin crashes and the solution was to update RAGENativeUI to the latest version, when I installed the latest version the plugin kept on crashing even when I loaded the plugin manually it crashed the game

[RagePluginHook.log](https://github.com/pnwparksfan/rph-live-lights/files/9546476/RagePluginHook.log)

 - Game version: 1.0.2699
 - RagePluginHook version: 1.96.1311.16365
 - Plugin version: 0.7.7534.881 or 0.7 RC

**Comment by pnwparksfan** [comment]
Unable to reproduce this issue. Works for me on the latest version of GTA with the latest version of RPH and RNUI.
