### ISSUE TITLE
Bug with latest version [1.0.8333.746]

### ISSUE THREAD

**Issue by BJDubb** [pnwparksfan/rph-live-lights#17]
**Describe the problem**
Launching with fresh install of RPH and LiveLights. RPH unable to load dll.

**To Reproduce**
1. Spawn
2. Press 'F4' to open rph console
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/47697544/198573212-2e85d214-b529-4409-8d89-02a44ecc9dee.png)

**Log file**
[RagePluginHook.log](https://github.com/pnwparksfan/rph-live-lights/files/9887817/RagePluginHook.log)

**System information (please complete the following information):**
 - Game version: 1.0.2699.16
 - RagePluginHook version: 1.99.1316.16417
 - Plugin version: 1.0.8333.746

**Comment by BJDubb** [comment]
Needed RageNativeUI

**Comment by pnwparksfan** [comment]
The requirement for RNUI is clearly listed in the readme :)
