### ISSUE TITLE
No live visual change

### ISSUE THREAD

**Issue by Kilian68** [pnwparksfan/rph-live-lights#7]
Hello, I hope you will answer.  I installed the plugins, but once in game, in any vehicle with rotating beacons, I can change the parameters via the menu, nothing changes on the vehicles, what to do?  My discord: Kilian#1196

**Comment by pnwparksfan** [comment]
Several people have reported this issue, which is a problem with the underlying RagePluginHook functionality for modifying sirens. We are not sure what exactly causes the issue, but at least two users have reported that doing a _full_ clean install resolved the issue for them. At any rate, it is not an issue with LiveLights itself.
