### ISSUE TITLE
siren note location

### ISSUE THREAD

**Issue by wolfrunner86** [pnwparksfan/rph-live-lights#8]
would it be possible to have the !-- Siren 1 -- placed before the  Item  tag so when you collapse the data you can see which is each siren

**Comment by pnwparksfan** [comment]
I do have this partially implemented, I will try to finish it whenever I do the next update/release.

**Comment by wolfrunner86** [comment]
ok cool, also thanks for the work, love this makes tweaking non els so much easier

**Comment by pnwparksfan** [comment]
Will be implemented in the next update (currently on import-export-improvements branch)
